config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_tasks
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destory'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @tasks = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
  end

  def edit
    @tasks = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to tasks_path
  end

  def destory
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit <%= @tasks.title %></h1>

<%= simple_form_for(@tasks) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit %>
  <% end %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>
<div class="task-list">
  <% @tasks.each do |task| %>
  <h5> <input type="checkbox"> <% task.completed %></input><%= link_to task.title, task_path(task) %></h5>
  <% end %>
</div>

<div class="add">
  <p><%= link_to 'Add a new task', '/tasks/new' %>
</div>

app/views/tasks/new.html.erb
<h1>Create a New Task</h1>

<%= form_for(@tasks) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
  <% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<%= link_to 'Edit Task', edit_tasks_path %>
<p><%= @task.details %></p>

<% if @task.completed? %>
      <div><i class="far fa-check-square"></i><span>This task is complete</span></div>
    <% else %>
      <div><i class="far fa-square"></i><span>This task has not been completed yet</span></div>
    <% end %>


<%= button_to "Delete", @task, :method => "delete", data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>


<p><%= link_to 'Back to List', tasks_path %></p>